services:
  postgres:
    image: postgres:16
    container_name: gocart_db
    environment:
      POSTGRES_USER: gocart
      POSTGRES_PASSWORD: gocart
      POSTGRES_DB: gocart
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
